version: 0.0
os: linux
files:
    - source: /
      destination: /home/ec2-user/environment/code-deploy-ux

permissions:
    - object: /
      pattern: '**'
      owner: ec2-user
      group: ec2-user

hooks:
    AfterInstall:
        - location: deploy/AfterInstall.sh
          timeout: 120
          runas: ec2-user
